name 'firewalld'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures firewalld'
long_description 'Installs/Configures firewalld'
version '0.1.0'
