name 'services'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures services'
long_description 'Installs/Configures services'
version '0.1.0'
